## Normal Equation

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("ex1data2.txt", names=["Size of House","Number of bedrooms","Price of the House"])
data.head()

Size of House  Number of bedrooms  Price of the House
0           2104                   3              399900
1           1600                   3              329900
2           2400                   3              369000
3           1416                   2              232000
4           3000                   4              539900

In [3]:
X = data.iloc[:,:2]
y = data.iloc[:,2:]
m=len(y)

In [4]:
X = np.append(np.ones([m,1]),X ,axis=1)
y = np.array(y).reshape(-1,1)
theta = np.zeros([3,1])

Xtranspose = X.transpose()

In [5]:
Xtranspose = X.transpose()
Xinverse = np.linalg.inv(np.dot(Xtranspose,X))
print(Xinverse)

[[ 3.99642990e-01 -7.36150728e-06 -1.14704720e-01]
 [-7.36150728e-06  5.01455797e-08 -2.93241497e-05]
 [-1.14704720e-01 -2.93241497e-05  5.46881227e-02]]


In [6]:
theta = np.dot(Xinverse,Xtranspose)
theta = np.dot(theta,y)
print(theta)

[[89597.9095428 ]
 [  139.21067402]
 [-8738.01911233]]


In [7]:
pred = np.array([1,1650,3])
price = np.dot(pred,theta)
print(price)

[293081.46433489]
